repos:
  - repo: git@github.com:pre-commit/pre-commit-hooks.git
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: git@github.com:psf/black.git
    rev: 24.4.2
    hooks:
      - id: black
        args: [--line-length=120]

  - repo: git@github.com:PyCQA/flake8.git
    rev: 7.1.0
    hooks:
      - id: flake8
        args: [--max-line-length=120]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args: [--config-file=pyproject.toml]

  - repo: git@github.com:charliermarsh/ruff-pre-commit.git
    rev: v0.4.10
    hooks:
      - id: ruff
        args: [--line-length=120]
