repos:
  - repo: git@github.com:pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: git@github.com:psf/black.git
    rev: 22.3.0
    hooks:
      - id: black
        args: [--line-length=120]

  - repo: git@github.com:PyCQA/flake8.git
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [--max-line-length=120]

  - repo: git@github.com:pre-commit/mirrors-mypy.git
    rev: v0.812
    hooks:
      - id: mypy

  - repo: git@github.com:charliermarsh/ruff-pre-commit.git
    rev: v0.0.241
    hooks:
      - id: ruff
        args: [--line-length=120]
